# 들어가기

## 파이썬

> 파이썬은 강력하고, 빠르다. 다른 것과 잘 어울린다. 어디서나 실행된다. 쉽게 배울 수 있다. 열려있다.

위의 글[^origin]은 파이썬의 공식 사이트(python.org)에 걸려있는 문구이다. 파이썬은 다양한 목적을 위해 활용할 수 있는 범용 컴퓨터 언어로 쉽게 배울 수 있는 인터프리터 언어이다.[^interpreter] 

파이썬(Python)은 네덜란드계 프로그래머인 귀도 반 로섬(Guido van Rossum)이 만들었다. 귀도 반 로섬은 마크 러츠(Mark Lutz)의 책[^marklutzbook] 서문에서 1989년 크리스마스 연휴에 연구실이 문을 닫아 취미삼아 새로운 컴퓨터 언어를 만들었다고 공개했다. 파이썬이라는 이름은 몬티 파이썬의 날아다니는 서커스(Monty Python's Flying Circus)라는 TV 프로그램에서 따왔다고 한다.[^namepython] 귀도는 파이썬의 큰 특징의 하나로 들여쓰기(indentation)를 들었다. 그 전까지 들여쓰기를 컴퓨터 언어의 구문론(syntax)에 적극적으로 도입한 경우가 거의 없었기 때문이다.[^abc] 귀도는 들여쓰기를 통해 소스 코드가 간결하고, 읽기 쉬어진다고 설명했다.

최근 데이터 사이언스에서 가장 많이 쓰이는 언어는 단연코 R과 파이썬이다. R은 처음부터 통계 분석을 위해 개발된 언어이고, 통계학자과 데이터 분석가들이 애용한다. 파이썬은 범용 프로그래밍 언어로 개발되었지만, 여러가지 데이터 분석용 패키지가 개발되면서 R과 함께 데이터 분석을 위해 가장 많이 사용되는 언어가 되었다. 최근에는 인공지능(AI) 개발 프레임워크인 텐서플로우나 파이토치를 활용하기 위해 파이썬을 사용하는 경우가 많다. 혹자는 R은 조금 규모가 큰 사업체에서, 파이썬은 스타트업과 같은 소규모의 사업체에서 주로 사용한다고 말한다. 필자의 경험에 따르면 대표적인 데이터 분석을 할 때에는 어떤 언어를 사용하더라도 큰 차이가 없다. 만약 조금 전문적인, 또는 최신의 통계 분석을 하고자 한다면 R이 낫다. 파이썬은 자연어 처리와 딥러닝에서 우위를 보인다.

[^origin]: Python is powerful... and fast; plays well with others; runs everywhere; is friendly & easy to learn; is Open

[^interpreter]: 컴파일 언어와 대비되는 말로 쓰여진 문장을 한 줄씩 읽고 번역해서 실행하는 프로그래밍 언어. 컴파일 언어는 모든 문장을 읽고 해석한 후 실행한다.

[^marklutzbook]: Programming Python

[^namepython]: 영어에서 파이썬(python)은 비단뱀을 의미하고, 고유명사 Python은 그리스 신화에 등장하는 거대한 뱀이다. 이런 엉뚱한 작명은 seaborn이라는 파이썬 시각화 패키지에서도 나온다. seaborn은 웨스트 윙이라는 정치 드라마에 등장하는 Samuel Norman Seaborn이라는 등장인물에서 따왔다고 한다. 

[^abc]: 들여쓰기는 프로그래밍 언어 ABC의 가장 큰 특징 중의 하나이다. 

본서는 파이썬을 활용하여 데이터 전처리 방법을 소개한다. 특히 R에서 파이썬으로 넘어오는 분석가를 위해 파이썬과 R을 비교해서 필자가 겪어던 실수를 반복하지 않도록 하였다. R을 사용하여 데이터 전처리를 해봤다면, 그 경험을 활용하여 파이썬을 활용한 데이터 전처리 방법을 좀더 쉽게 배울 수 있다. 하지만 R에서의 경험이 발목을 잡기도 한다. 따라서 단순히 코드 수준의 활용 방법이 아니라 R과 파이썬의 차이를 개념/원리 수준에서 설명하여 R 경험자도 쉽게 파이썬을 배울 수 있도록 하였다. 

## 파이썬의 기반 시설

파이썬은 컴퓨터와 운영체제를 기반으로 돌아간다. 컴퓨터의 CPU 종류, 빠르기, 메모리의 크기와 같은 기본적인 컴퓨터 사양과 운영체제의 종류, 버전 등을 확인해보자. 운영체제 커맨드라인에서 아래와 같이 실행하면 CPU, 메모리, 운영체제에 대한 정보를 출력하고, 파일 `00_get_pcinfo.py`를 `get_pcinfo.py`로 복사한다.

```{bash}
python 00_get_pcinfo.py
```

`get_pcinfo.py`는 파이썬 안에서 `import get_pcinfo`로 실행할 수 있다. 

```{python}
import get_pcinfo
# import 한 후에 시스템 사양을 출력하려면 .main() 를 실행해야 한다.
# 그 이유는 뒤에서 설명된다.
get_pcinfo.main() 
```

### 운영체제(OS; Operating System)에서 전달된 정보

파이썬은 운영 체제 위에서 실행된다. 사용자가 운영 체제에서 파이썬으로 어떤 정보를 전달하는 방법은 크게 두 가지를 생각해볼 수 있다. 

* 운영체제의 환경 변수 : 운영체제의 지속적인 특성은 보통 환경 변수에 저장된다. 
* 파이썬 실행 시의 인자 : 파이썬 모듈 `a.py`를 운영체제에서 실행하기 위해 `python a.py`로 쓴다. 만약 추가적인 정보를 전달하고자 한다면 `python a.py 100`, `python a.py --sum 100 200` 등과 같이 쓸 수 있다.

#### 윈도우에서 운영 체제의 환경 변수 변경하기

윈도우 10의 GUI(Graphic User Interface)를 사용하여 환경 변수 Path를 변경하고자 한다면, 다음과 같이 윈도우의 메뉴를 찾아들어간다(자세한 내용은 인터넷에서 "윈도우 환경 변수 설정"으로 검색하면 손쉽게 확인할 수 있다).

`시작 - 검색 : "변수" - "시스템 환경 변수 설정" 선택 - 고급 탭 - 환경변수 - 시스템 변수(또는 사용자 변수) - 변수:Path(현재 변수 Path를 확인할 수 있다. 윈도우 폴더가 ;를 구분자로 나열되어 있다.) - 편집 - 새로 만들기 - 추가`

윈도우 명령 프롬프트(`cmd`)에서 명령를 입력하여 환경변수를 설정할 수도 있다.

```{cmd language="cmd"}
rem 현재 환경 변수 출력하기 위해서는 path를 쓴다.
path 

rem 윈도우에서 환경 변수는 변수명 앞뒤에 %를 붙여서 사용할 수 있다.
echo %path%
	
rem 사용자 환경 변수 path에 c:/temp "일시적" 추가
rem 기존의 환경 변수 내용는 %path%에 담겨 있다.
set path=%path%;c:\temp;  
	
rem 사용자 환경 변수 path에 c:\temp 추가
setx path "%path%;c:\temp"  
	
rem 시스템 환경 변수 path에 c:\temp 추가
rem (명령 프롬프트를 관리자 권한으로 실행해야 함)
setx /M path "%path%;c:\temp"  
```

#### 윈도우 파이썬에서 운영 체제의 환경 변수 일시적으로 수정하기

`os.environ['path']` 또는 `os.environ['Path']` 등으로 환경변수 `PATH`(윈도우는 대소문자를 구분하지 않는다)를 확인할 수 있다. `os.environ['path']`를 직접 수정할 수 있지만 그 효과는 현재 파이썬에서만 유효하다.

```{python}
import os
os.environ['path'] # 또는 os.environ.get('path')
paths = os.environ['path'].split(';')
os.environ['path'] = ';'.join(paths + ['c:/temp']) # 새로운 폴더
```

#### 윈도우/유닉스 파이썬 실행 인자 확인

```{python}
import sys
sys.argv
# python test.py 100을 실행하면
# sys.argv = ['test.py', '100']
```

#### 유닉스 기반 운영 체제의 환경 변수 변경하기

유닉스에서 환경 변수 `PATH`를 변경하는 방법은 다음과 같다. `$PATH`은 환경변수 `PATH`를 의미한다(윈도우의 경우 `%PATH%`). 그리고 환경변수에서 폴더를 구분하기 위해 구분자로 `:`를 쓴다(윈도우는 `;`). `#`은 주석을 의미한다.

```{bash}
echo $PATH  # 현재 환경변수 PATH 확인
# /usr/temp를 환경변수 PATH에 추가
export PATH=$PATH:/usr/temp
```

#### 유닉스 기반 파이썬에서 운영 체제의 환경 변수 일시 수정하기

```{python}
import os
os.environ['PATH'] # 또는 os.environ.get('PATH')
# 윈도우의 경우 path, Path, PATH 모두 가능하지만,
# 유닉스 기반의 운영체제에서 대소문자를 구분하기 때문에 꼭 PATH를 쓴다
paths = os.environ['PATH'].split(':')
# 새로운 폴더 /usr/tmp 추가 : 유닉스는 대소문자를 구분한다.
os.environ['PATH'] = ':'.join(paths + ['/usr/tmp']) 
```

## 참고문헌

* https://www.python.org/doc/essays/foreword/
* https://www.python.org/doc/essays/foreword2/
